# Multi-Platform AI Orchestration Configuration

# Core Orchestration Settings
orchestration:
  max_concurrent_tasks: 50
  task_timeout_seconds: 300
  retry_attempts: 3
  enable_emergent_intelligence: true
  subscription_tier_required: "premium"
  distributed_mode: true

# Subscription Management Settings  
subscription:
  usage_tracking_enabled: true
  billing_cycle_days: 30
  free_tier_limits:
    max_concurrent_tasks: 2
    max_agents: 1
    api_rate_limit: 10
  premium_tier_limits:
    max_concurrent_tasks: 50
    max_agents: 20
    api_rate_limit: 1000

# Agent Coordination Settings
agents:
  initial_agent_count: 4
  max_agents: 100
  coordination_strategy: "emergent_adaptive"
  health_check_interval_seconds: 60
  scaling_strategy: "demand_based"

# Emergent Intelligence Settings
intelligence:
  enable_pattern_discovery: true
  enable_adaptive_learning: true
  enable_predictive_modeling: true
  enable_anomaly_detection: true
  min_pattern_confidence: 0.7
  max_patterns_stored: 1000
  learning_data_retention_days: 30
  model_update_frequency_minutes: 60

# Infrastructure Settings
infrastructure:
  enable_monitoring: true
  metrics_collection_interval: 30
  log_level: "INFO"
  enable_distributed_tracing: true

# API Settings
api:
  enable_rest_api: true
  enable_websocket: true
  cors_enabled: true
  rate_limiting_enabled: true
  authentication_required: true