# Authentication Configuration Template
# Copy to auth_config.yaml and fill in your credentials

github:
  token: "YOUR_GITHUB_TOKEN"
  app_id: "YOUR_GITHUB_APP_ID"
  client_id: "YOUR_GITHUB_CLIENT_ID"
  client_secret: "YOUR_GITHUB_CLIENT_SECRET"
  webhook_secret: "YOUR_GITHUB_WEBHOOK_SECRET"

google:
  project_id: "YOUR_GOOGLE_PROJECT_ID"
  client_id: "YOUR_GOOGLE_CLIENT_ID"
  client_secret: "YOUR_GOOGLE_CLIENT_SECRET"
  service_account_path: "path/to/service/account.json"
  ai_api_key: "YOUR_GOOGLE_AI_API_KEY"

microsoft:
  tenant_id: "YOUR_AZURE_TENANT_ID"
  client_id: "YOUR_AZURE_CLIENT_ID"
  client_secret: "YOUR_AZURE_CLIENT_SECRET"
  subscription_id: "YOUR_AZURE_SUBSCRIPTION_ID"
  openai_api_key: "YOUR_OPENAI_API_KEY"

firebase:
  project_id: "YOUR_FIREBASE_PROJECT_ID"
  service_account_path: "path/to/firebase/service/account.json"
  api_key: "YOUR_FIREBASE_API_KEY"

jules:
  api_endpoint: "YOUR_JULES_API_ENDPOINT"
  api_key: "YOUR_JULES_API_KEY"
  webhook_secret: "YOUR_JULES_WEBHOOK_SECRET"